import 'package:antinvestor_auth_runtime/src/config/resolve_config.dart';
import 'package:antinvestor_auth_runtime/src/errors/auth_error.dart';
import 'package:antinvestor_auth_runtime/src/worker/token_worker.dart';
import 'package:flutter/services.dart' show PlatformException;
import 'package:flutter_web_auth_2/flutter_web_auth_2.dart';

/// Result returned from a completed OAuth leg.
///
/// `state` is the value the IdP echoed on the callback. Callers verify
/// it against the `state` they generated in [TokenWorker.prepareAuth].
class OAuthResult {
  const OAuthResult({required this.code, required this.state});

  final String code;
  final String state;
}

/// Function that drives the system-browser leg. Defaults to
/// [FlutterWebAuth2.authenticate]; tests inject a fake.
typedef WebAuthFn = Future<String> Function({
  required String url,
  required String callbackUrlScheme,
  FlutterWebAuth2Options options,
});

/// Drives the OAuth browser leg cross-platform.
///
/// Opens [AuthorizeRequest.url] in the system browser via
/// `flutter_web_auth_2`, captures the redirect URI, and extracts `code`
/// and `state` from the query string. PKCE verifier, state, and nonce
/// are generated by [TokenWorker.prepareAuth] and round-trip through
/// [AuthorizeRequest] — this class does no crypto of its own.
///
/// Cross-platform: iOS, Android, macOS, web, Windows, Linux. On the web,
/// the IdP login page may use FedCM (`navigator.credentials.get`) for
/// federated identity — that's a server-side capability of the IdP page;
/// this client just opens the URL and is FedCM-transparent.
class OAuthFlow {
  OAuthFlow({WebAuthFn? webAuth})
      : _webAuth = webAuth ?? FlutterWebAuth2.authenticate;

  final WebAuthFn _webAuth;

  /// Drives the browser leg and returns the OAuth `code` + echoed
  /// `state`. Maps user-cancel to [AuthErrorCode.oauthUserCanceled],
  /// every other failure to [AuthErrorCode.oauthFailed].
  Future<OAuthResult> authorize(
    ResolvedConfig cfg,
    AuthorizeRequest prepared,
  ) async {
    final redirect = Uri.parse(cfg.redirectUri);
    final scheme = redirect.scheme;
    if (scheme.isEmpty) {
      throw AuthError(
        AuthErrorCode.invalidConfig,
        'redirectUri is missing a scheme: ${cfg.redirectUri}',
      );
    }

    final options = scheme == 'http' || scheme == 'https'
        ? FlutterWebAuth2Options(
            httpsHost: redirect.host,
            httpsPath: redirect.path,
          )
        : const FlutterWebAuth2Options();

    String callback;
    try {
      callback = await _webAuth(
        url: prepared.url,
        callbackUrlScheme: scheme,
        options: options,
      );
    } on PlatformException catch (err) {
      if (_isCancel(err)) {
        throw AuthError(
          AuthErrorCode.oauthUserCanceled,
          'user cancelled OAuth flow',
          cause: err,
        );
      }
      throw AuthError(
        AuthErrorCode.oauthFailed,
        'OAuth authorize failed: ${err.code}',
        cause: err,
      );
    } catch (err) {
      throw AuthError(
        AuthErrorCode.oauthFailed,
        'OAuth authorize failed',
        cause: err,
      );
    }

    final params = Uri.parse(callback).queryParameters;

    final error = params['error'];
    if (error != null && error.isNotEmpty) {
      final desc = params['error_description'] ?? error;
      if (error == 'access_denied' || error == 'user_cancelled') {
        throw AuthError(AuthErrorCode.oauthUserCanceled, desc);
      }
      throw AuthError(AuthErrorCode.oauthFailed, desc);
    }

    final code = params['code'];
    final state = params['state'];
    if (code == null || code.isEmpty) {
      throw AuthError(
        AuthErrorCode.oauthFailed,
        'OAuth callback missing code',
      );
    }
    if (state == null || state.isEmpty) {
      throw AuthError(
        AuthErrorCode.oauthFailed,
        'OAuth callback missing state',
      );
    }
    return OAuthResult(code: code, state: state);
  }
}

bool _isCancel(PlatformException err) {
  final code = err.code.toUpperCase();
  return code == 'CANCELED' || code == 'CANCELLED' || code.contains('CANCEL');
}
