
[CouldNotCheckContactExists]
one="Could not check contact exists"
[CouldNotCreateProfileByContact]
one="Could not create profile by contact provided"
[CouldNotCreateLoginDetails]
one="Could not create login details"
